### ISSUE TITLE
Use Qiniu together with Solr Thumbnail

### ISSUE THREAD

**Issue by Carolusian** [glasslion/django-qiniu-storage#18]
If I use Qiniu Storage at the backend with packages which use solr thumbnail, then the image cannot be displayed properly.

e.g.   

```
{% thumbnail image.original "440x400" upscale=False as thumb %}
              <img src="{{ thumb.url }}" alt="{{ product.get_title }}" />
{% endthumbnail %}
```

The above code will change the url to https://{$url}/media/cache/79/07/79079b0cfd2b4a867b4b7cea3d072f0b.jpg
where the image does not really exist.

Amazon S3 have solved this issue. I am thinking whether Qiniu can solve it as well.

**Comment by glasslion** [comment]
I think this is sorl-thumbnail's problem , not qiniu-storage
