### ISSUE TITLE
富文本编辑器的支持

### ISSUE THREAD

**Issue by jimczj** [glasslion/django-qiniu-storage#20]
作者你好，你的作品确实很棒，不过有一点问题，好像对富文本编辑器（比如djangoUeditor）的图片支持不够，无法让图片走七牛，还是我的使用有问题。希望你能尽快回复我，如果是支持不够，我最近会pull request到这里

**Comment by glasslion** [comment]
django-qiniu-storage 只负责文件存储。 djangoUeditor 不支持，是运维其没有没遵守 django 的规范 。 那个项目代码极烂， 真不建议用。
