### ISSUE TITLE
假如我原来站点就有本地文件, 可以平和迁移到七牛吗?

### ISSUE THREAD

**Issue by joway** [glasslion/django-qiniu-storage#23]
是否有API可以直接把原先的所有文件给同步到七牛上去? 自己写脚本同步怕不能和框架很好兼容, 目录不知道放在哪里

**Comment by glasslion** [comment]
目前没有这样的 API。存储迁移的方案设计和存储数据量的大小， 迁入方和迁出方分别提供了哪些 API, 工具有很大关系，不太可能给一个统一的迁移方法。

如果你们原来文件是存在本地磁盘的， 可以考虑用 [qshell](http://o9gnz92z5.bkt.clouddn.com/code/v6/tool/qshell.html)
 更详细的情况， 可以咨询七牛客服。

**Comment by joway** [comment]
Thanks！
