### ISSUE TITLE
下载和上传文件的时候，实际还会经过运行 django 的 server 吗

### ISSUE THREAD

**Issue by FingerLiu** [glasslion/django-qiniu-storage#30]
我们是用 Django REST Framework 前后端分离进行的开发。
如果用 django-qiniu-storage 存七牛的话，
上传和下载的文件实际数据是   浏览器 --  django server -- 七牛 server 这样经过 django server 中转
还是直接 浏览器 -- 七牛 server ??

**Comment by glasslion** [comment]
上传一定会经过 server 中转， 出于安全考虑，肯定不能允许浏览器端直接上传的。

下载的话， 看你怎么用了。 你当然可以在 server 端 用 storage的 open() 方法去读 七牛上文件内容。 但一般来说， 还是直接返回给客户端 文件的 url 。浏览器通过七牛的url 下载就不经过 django 了。

**Comment by FingerLiu** [comment]
@glasslion 这样啊，多谢回答。
最后采用了如下流程没经过 django 中转：


1. client 从 django 获取七牛的 token
2.client 拿这个 token 将文件上传到七牛
3. 七牛接到文件后 callback 通知 django
4. django 接收到回调后存文件名等信息。

**Comment by glasslion** [comment]
@FingerLiu 这样的话， client 可以拿这个token 做很多坏事了

**Comment by FingerLiu** [comment]
生成这个 token 的时候，会有七牛权限控制，比如你申请的是针对 key1 的 download token, 那么你只能用来下载 key1 这个文件，而且默认有效期好像是1个小时。
