### ISSUE TITLE
qiniu python sdk需要升级

### ISSUE THREAD

**Issue by youqingxiaozhua** [glasslion/django-qiniu-storage#34]
在使用Supervisor的过程中遇到问题：
Permission denied: '/root/.qiniu_pythonsdk_hostscache.json'

经查：https://github.com/qiniu/python-sdk/issues/225

七牛官方已经升级了SDK修复问题，更新下sdk应该可以解决

**Comment by glasslion** [comment]
为了照顾到大部分用户， 本项目没有对 七牛 sdk 的版本有太强的依赖。 目前的 qiniu>=7.1.0 也是采用了能兼容 Python3 的最低版本。 如果你需要最新的七牛sdk， 自己升级就行了
