### ISSUE TITLE
怎样设置上传到文件的大小？

### ISSUE THREAD

**Issue by yuzg667** [glasslion/django-qiniu-storage#39]
问题1:怎样设置上传文件的大小？比如限制上传图片最大只能2MB，怎样设置。
问题2:上传图片压缩功能，有吗，怎样使用？
谢谢

**Comment by bigtotorouk** [comment]
这个问题很关键啊 。。。
models.ImageField(verbose_name="封面图片", null=True, blank=True,
                                upload_to='topic/%Y/%m', storage=QiniuMediaStorage(),
                                processors=[ResizeToFit(1000, 1000)], format='JPEG', options={'quality': 80})
我这样搞出错 。请指教

**Comment by glasslion** [comment]
@bigtotorouk 限制文件大小的方式有很多， 可以 subclass ImageField 或 在validator  里做限制。 一般不在文件存储层做限制。

**Comment by glasslion** [comment]
限制上传文件大小的方法很多， 光是在 Django 里就可以分别在 field, form, storage 层去做限制。

建议首先在前端判断一下文件大小挡掉超大文件， 这样对用户比较友好。
后端的话， 如果是要限制某几个form 图片的大小， 用 form validator 做。 如果是要限制全局文件大小， 可以重载 storgae class 的 `_save`  或用七牛的 [上传策略](https://developer.qiniu.com/kodo/manual/1206/put-policy).
以上方法只能防止超大文件不被上传到七牛， 但仍然不能阻止文件被上传到Django 服务器本身。 Django 对此做了一定的防范， 对于超出 FILE_UPLOAD_MAX_MEMORY_SIZE 的文件会写到磁盘， 而不是内存里的。但这样面对恶意攻击还是很脆弱的，  因此通常是建议在 Nginx 里再限制上传文件的大小。
