### ISSUE TITLE
use pc upload  image  time_out

### ISSUE THREAD

**Issue by x931890193** [glasslion/django-qiniu-storage#42]
qiniustorage.utils.QiniuError: status_code:-1, x_log:None, error:('Connection aborted.', timeout('timed out',)), text_body:None, _ResponseInfo__response:None, req_id:None, exception:('Connection aborted.', timeout('timed out',))

**Comment by glasslion** [comment]
Your error message is not very hepful.Reopen the issue if you have detailed infos. However it does not look like a qiniustorage bug
