### ISSUE TITLE
media路径错误

### ISSUE THREAD

**Issue by yaozhifeng** [glasslion/django-qiniu-storage#8]
媒体文件的url表示有错误，media出现两次。例如：
http://xxxxxxx.clouddn.com/media/media/logo/2015/05/02/sheep.png
实际文件所在位置只有一个media。

是哪里设置不对吗？static文件就很正常。

我的设置：
DEFAULT_FILE_STORAGE = 'qiniustorage.backends.QiniuMediaStorage'
STATICFILES_STORAGE  = 'qiniustorage.backends.QiniuStaticStorage'

**Comment by glasslion** [comment]
已修复
